### ISSUE TITLE
[management] Labels?

### ISSUE THREAD

**Issue by Chovin** [Cog-Creators/Cog-Board#10]
Cog-Board Labels?

Proposed:

- [x] bounty
- [x] claimed
- [x] edit (or we can just use the enhancement label)
- [x] info-needed
- [ ] api-or-util

As well as category-based labels
- [x] integration
- [x] audio
- [x] fun
- [x] moderation
- [ ] tools

@Kowlin you seem pretty good at organizing things into labels. Do you think you can help get this on the right track?

**Comment by Kowlin** [comment]
Lel, sure will do. I'll throw it out with a contribution guide.

**Comment by Kowlin** [comment]
Clarify on Edit?

**Comment by Chovin** [comment]
ah sorry, I meant it's a request for an enhancement of a current cog

**Comment by Kowlin** [comment]
I see ;)

**Comment by Kowlin** [comment]
Forgot to mark as done.
