### ISSUE TITLE
ServerInfo

### ISSUE THREAD

**Issue by MagicNinja123** [Cog-Creators/Cog-Board#12]
Better Server Info

**Comment by Nerdietony** [comment]
Like what?

**Comment by MagicNinja123** [comment]
Vervication Level 
How Many People Are Online
How Many Roles 
server id
Custom Emotes 
AFK Timout Time
Vervication Level

**Comment by Chovin** [comment]
why custom emotes and why AFK timeout?
I wouldn't mind seeing the 1st x highest roles though

**Comment by Jan200101** [comment]
I did make a better version of serverinfo in my Info cog which has the things you mentioned

**Comment by Chovin** [comment]
please link and @MagicNinja123 let us know if that satisfies your needs

**Comment by Jan200101** [comment]
Repo Link : https://github.com/Jan200101/Sentry-Cogs

Code : https://github.com/Jan200101/Sentry-Cogs/blob/master/info/info.py#L220

**Comment by MagicNinja123** [comment]
Well Look At It

**Comment by MagicNinja123** [comment]
@Jan200101 Do i Have to Unload The General Cog

**Comment by Chovin** [comment]
@MagicNinja123 this is the second time. Please take support questions to the creator's repo or his support channel on the support server

**Comment by MagicNinja123** [comment]
Sorry
