### ISSUE TITLE
Faction Points cog

### ISSUE THREAD

**Issue by dreamscape195** [Cog-Creators/Cog-Board#139]
## Description of cog:

A cog that can keep track of "points" belonging to factions you can set. Ideally:

**Admins would be able to:**
- [p]points create [Faction Name] | _To create a faction that can have a points total._ 
- [p]points delete [Faction Name] | _To delete a faction and associated points._ 
- [p]points set [Faction Name] [number of points] | _To set a faction's points to a specific number._ 

**Mods (and above) would be able to**
- [p]points add [Faction Name] [number of points] | _To add the specified number of points to that faction's total._
- [p]points remove [Faction Name] [number of points] | _To remove the specified number of points from that faction's total._

**Everyone would be able to**
- [p]points check [Faction Name] | _To get a bot message in the channel that says something like "[Faction Name] has [Current Points] points!" (preferably in a multiple line block quote)._
- [p]points checkall | _To get a bot message that shows all current factions' current points (preferably in a multiple line block quote)._

**Please also, if possible**
- Points can't go below zero, or, points being able to go below zero or not is able to be toggled. 
- Faction names when giving / taking away points are not case sensitive.
- The name of the "points" could be changed by the owner (say, if they wanted to call it karma, or exp).
- The [p]points checkall command could display the factions leaderboard style; in descending order by current total of points.
- Alt faction names ([p]points setalt [Faction Name] [Alt Name] | and | [p]points delalt [Faction Name] [Alt Name]) might be nice, so instead of "[p]points add BestFaction411 10" they could do "[p]points add BF411 10" which adds the 10 points correctly to bestfaction411, because they added BF411 as an alt name for that faction.
- Owner could do [p]points reset | To reset ALL factions to zero at the same time (maybe with an "Are you sure? This will reset the points of all factions to zero. If you want to proceed, type [p]points reset yes" message).

**Additional things that might be neat** _(but are by **no means** necessary)_
- The exact display message for checking points could be altered by the owner (eg. "[Faction Name] has [Current Points] points!" could be altered to say "[Faction Name] has earned [Current Points] big fat stinking points." instead when the points are checked). 
- Triggers could be set to automatically give or take away points. Eg. if someone says "ten points to [faction name]" that could be set to automatically add 10 points to a particular faction. 

I personally wouldn't even use either of these last two points above, since I'm the one asking for a default message I already like anyway in regards to the first one, and since I only want mods+ being able to add points anyway in regards to the second; but they might be neat for other people looking for a similar cog, I dunno. They probably aren't worth the work - it's _entirely_ fine if these two bullet points aren't addressed. 

## API's or other information for cog:

I have no idea what this means I'm sorry

## Other info (Bounty, issues, ETC):

I have no idea how difficult something like this is so I hesitate to throw numbers into the void, but am entirely willing to discuss payment. If it's something I can afford, I will absolutely pay for the work necessary to make this a cog. 
- Add me on Discord: Dreamscape195#3539 

(but please do comment here first so I can double check, and maybe also send me a message saying who you are/what it's about on discord itself, otherwise I might deny the request by mistake)

**Comment by Sebass13** [comment]
First off, I appreciate that you have a fully fleshed out idea for what you want the cog to be, especially related to the layout of permissions. This is an ideal request, as I know exactly what I'm going to try to do for you. I added you on Discord to discuss, my ID is Sebass#6296.

**Comment by dreamscape195** [comment]
Oh, I failed to reply here before, but for anyone else reading this - Sebass and I are now in contact regarding my requested cog (: 

I'll close once the cog is finished and I've paid the bounty.

**Comment by dreamscape195** [comment]
My cog is done and works beautifully. Sebass did a great job :) Thank you!
