### ISSUE TITLE
Mention / Keyword Tracker

### ISSUE THREAD

**Issue by clovisd** [Cog-Creators/Cog-Board#27]
Cog that tracks when a certain keyword/username was said in chat and notifies the user that they were mentioned (or a keyword was mentioned). This could just be a PM (if enabled) where the user gets a message that tells them the server, the person, the channel, and the time the message was sent. 

For example, Discord notifies me if someone where to do @clovisd but it wouldn't notify me if someone just said clovisd in chat. This would let the bot do that.

Thanks!

**Comment by palmtree5** [comment]
I can definitely see how this would be nice on mobile as to my knowledge, one can't see a list of messages they're mentioned in on mobile at the moment

**Comment by clovisd** [comment]
I think it would also be useful if you have your server chat linked to a different platform/game/server where @ mentions aren't available. ;)

**Comment by palmtree5** [comment]
I'm gonna work on this, at least on the mentions side of things

**Comment by palmtree5** [comment]
@clovisd Mention tracker is now in my repo
