### ISSUE TITLE
Delete Cog

### ISSUE THREAD

**Issue by MagicNinja123** [Cog-Creators/Cog-Board#28]
* Description of cog: a Cog That Give You The Abilty To Delete Built In ( The Bot Or a Cog ) Comamnds , However You Dont Lose The Command The Bot Will Save The Command You Delete It as Another Command ( You Can Find What The Command Was Changed To By Doing another Command Such As `[p]deletecomlist`

**Comment by Nerdietony** [comment]
Isn't there already a disable command?

**Comment by Chovin** [comment]
instead of "Delete" I think he means "Rename"

**Comment by Nerdietony** [comment]
Isn't there an alias cog?

**Comment by MidnightMafia** [comment]
https://twentysix26.github.io/Red-Docs/red_guide_aliases/

Alias I probably what you want.

**Comment by Nerdietony** [comment]
is* and i'm not asking for alias.

**Comment by palmtree5** [comment]
Uh, alias is exactly what you asked for when saying "Isn't there an alias cog?"

**Comment by Kowlin** [comment]
I'm considering to close this, there already is ``command disable`` and that works fine, is build into red and best of all. is persistent between bot sessions without any effort

**Comment by MagicNinja123** [comment]
I Want To Rename The Command Not Disable It..

**Comment by palmtree5** [comment]
you're looking for `[p]alias add`

Example: http://i.imgur.com/MjpqmlY.jpg
