### ISSUE TITLE
Raid Group Scheduler

### ISSUE THREAD

**Issue by OzForceOne** [Cog-Creators/Cog-Board#4]
Something that would allow server members to create events, track those who say they will be present.  

Like a Raid group forming tool.  Allow multiple events to be created. Date and time with a mention or DM to all people who signed up to remind them of the event as it approaches.  

*Edit:
Assigned to @palmtree5 
-- Kowlin*

**Comment by palmtree5** [comment]
Like the idea and will work on this. One question though, who should be able to create events? Only people with mod role or above or would everyone in a server be able to create an event?

**Comment by IamCLY** [comment]
How about make the permission we can choose/toggle later? Coz every server have different needs. Personally I will choose people with mod role or above but it will not works if the server is for open community.

**Comment by Chovin** [comment]
sounds like the permissions cog should handle that part then?

**Comment by skeith** [comment]
why not use a whitelist method for the one who will be able to create the events? rather than depending on external cog

**Comment by palmtree5** [comment]
Done with https://github.com/palmtree5/palmtree5-cogs/commit/d22dd1d83858e462a07e2a84936d1f037bf43d43

Events can be created by anyone by default but you can restrict by setting a specific role `[p]eventset role`. If a role is set, only that role, the server's mod and admin roles, and the server owner can create events. A channel can be specified for the notifications to be posted to `[p]eventset channel`. When the event's start time rolls around, the bot will send a message in the configured channel as well as sending a DM to all participants who signed up via `[p]joinevent`

Events are created using `[p]eventcreate`. It's a wizard and the event is only created if all parts of the wizard are completed successfully (the 3 parts are title, the amount of time remaining between event creation time and event start time, and a description of the event which must be no more than 750 characters)

**Comment by Chovin** [comment]
@OzForceOne please close the issue if this is sufficient
