### ISSUE TITLE
Lyrics 

### ISSUE THREAD

**Issue by Brandjuh** [Cog-Creators/Cog-Board#42]
## Description of cog:
Search for song and post songtext. 

## APIs or other information for cog:
https://www.programmableweb.com/category/lyrics/apis?category=20278

Idea came from the patron channel where somebody was posting songtext. That brings me to this Idea. 

## Other info (Bounty, issues, ETC):

General use for music fans and fun tool.
Possible issues: character post limit 
Non time expertations or Bounty from my side. I wont use it but would be a fun thing to have. 

Sorry for bad text, 48+ hours awake and not able to use computer. Phone is messing with auto correct.

**Comment by NekoTony** [comment]
I could do this...

**Comment by Brandjuh** [comment]
Side question: I can not edit the post? Want fix typos

**Comment by NekoTony** [comment]
I would like the fix typos.

**Comment by Sitryk** [comment]
I currently have a simple lyrics searching cog in my repo if you'd like to check it out: https://github.com/Sitryk/Sitryk-Cogs/

**Comment by palmtree5** [comment]
Closed @Sitryk's request
