### ISSUE TITLE
Random Dad joke - icanhazdadjoke

### ISSUE THREAD

**Issue by LordHighfixxer** [Cog-Creators/Cog-Board#44]
## APIs or other information for cog:
https://icanhazdadjoke.com/about

**Comment by UltimatePancake** [comment]
Done deal.

https://github.com/UltimatePancake/Pancake-Cogs

(cogs.red should be updating that soon)

**Comment by UltimatePancake** [comment]
Yup, there it is.
https://cogs.red/cogs/UltimatePancake/Pancake-Cogs/dadjokes/
