### ISSUE TITLE
Bump cog

### ISSUE THREAD

**Issue by MrRay70915** [Cog-Creators/Cog-Board#46]
## Description of cog:A bump cog
Make it so in the main server that the bot is in you make channel were people that have the bot can do [p] bump to promote the server and the bot grabs the description from the default channel and creates a instant invite.

## APIs or other information for cog:
https://cdn.discordapp.com/attachments/291265866715103232/314789024898351104/Screenshot_20170518-113858.png

**Comment by Kowlin** [comment]
Why, we're not a public bot. There is no use for this... And there will never be any use for it, since he. We do not have a list of servers since A: We do not advertise servers. And B: Every Red instance is unique.

Just my 2 cents on it.

**Comment by palmtree5** [comment]
My thumbs up is a second on @Kowlin's comment. As such, I'm closing this

**Comment by palmtree5** [comment]
After further consideration, I'm reopening this. I presume this is supposed to be specific to the instance of the bot and that there would be a command (owner-only) to set the main server?

**Comment by Real-Wizard** [comment]
https://github.com/Real-Wizard/Wizard-Cogs has been made but no command for adding id u will have to add from code https://github.com/Real-Wizard/Wizard-Cogs

**Comment by palmtree5** [comment]
FYI: Real-Wizard/Wizard-Cogs/pull/1 adds a command to set the id. Not a big fan of instructing users to manually edit files as it can lead to difficulties in updating

**Comment by Real-Wizard** [comment]
Added your edits, thatnk you
