### ISSUE TITLE
Card Trading/Marketplace

### ISSUE THREAD

**Issue by KrisDLuna** [Cog-Creators/Cog-Board#52]
## Description of cog:
Cog name: tcgmkt
A cog that allows TCG players to easily search for and trade cards with others.
* This cog should work for all TCGs where cards have unique identifiers (eg. a Card ID), but doesn't necessarily need to have a fail-safe measure in the case of duplicate Card IDs from different TCGs.

The basic idea here is to let users easily search for cards, find a trader, then they can PM the trader to express interest.

## APIs or other information for cog:
Core commands (all commands should be made available to use in PM unless specified otherwise)
- `tcgmkt help`
Command help message.
List all sub-commands.
- `tcgmkt pm`
Admin-only command.
PM toggle.
If toggle is on; limit bot to send all output via PM only.
- `tcgmkt add <CARD ID> <QUANTITY>`
Add own listing of cards available for trade.
Needless to say, this should have a `tcgmkt del` command as well.
- `tcgmkt <CARD ID>`
Ability to search for card and list all available traders
If card is available, print something like: `<CARD ID> available from: trader1, trader2, trader3`
Else, print: `No listings for <CARD ID>!`
Maybe also print total of <QUANTITY>?
- `tcgmkt <@USER>`
Ability to search for all listings belonging to mentioned user - or yourself if command missing mention.
Print something like: `Listings <CARD ID>,<QUANTITY> | <CARD ID>,<QUANTITY>`
Else, print: `No listings from <USER>!`

Extra functions (I apologize if any are technically impossible)
- `tcgmkt feed`
Toggle auto-announce new listing in channel, like a news feed.
Print something like: `<USER> just listed <QUANTITY> <CARD ID>!`
- `tcgmkt price <CARD ID>`
Calculate average price of card from all listings.
This will introduce a new <PRICE> array and we will also need to give users a command to set prices for their (unique) cards.
More features can be branched as a result of this, you're welcome to get creative.
- `tcgmkt ban <CARD ID>`
Admin-only command.
Disallow new listings of this card.
- `tcgmkt alias <CARD ID> <ALIAS>`
Admin-only command.
Create an alias for this card so that users can replace <CARD ID> with <ALIAS>.
Maybe could also make bot output a card's alias in place of its card ID wherever possible.

## Other info (Bounty, issues, ETC):
First glances, the JSON database should contain: SERVER ID, USER ID, CARD ID, QUANTITY, ALIAS, PRICE
"Marketplaces" should be unique to each server. Listings should be unique to each user.
It's gonna be a mess of nested array/objects.

I intend to work on this myself eventually if no one takes it, but would gladly offer a bounty if anyone would be so kind to do this for me.
Bounty will be paid in USD via Paypal/giftcards ONLY, you can quote your own price if you feel you deserve more beer.
Core functionality = $50
Extra features = +$50
Clear organized code with comments to make it easy-to-understand = +$20-50 (will be judged)

**Comment by palmtree5** [comment]
I'll work this one
