### ISSUE TITLE
Reverse Image Search Cog

### ISSUE THREAD

**Issue by MadamJazzy** [Cog-Creators/Cog-Board#56]
## Description of cog:
I have been trying to develop a cog that does reverse image search on the major networks and returns the status in the chat. It should use Sauce.nao, google, and tineye for sure cause these are the most popular. 
<your description here>
I already have code for this cog and it even has code to try and search iqdb.org but they have shut down their API access so that needs to be removed. The main problem that i am having with the code and that requires help is that tineye does not seem to want to work and same issue with google. 
## API's or other information for cog:
Uses BeautifulSoup to scrape for result and displays in chat with link. 
Requires BS4 (pip3 install BS4) to work 
<APIs and integrations here>

## Other info (Bounty, issues, ETC):
i have been working on this for quite some time with a friend but i can't seen to get it right. Not the best python coder (i get by though) so I am putting it here to try and get some assistance and trusting that I wont be kept outta the loop when it comes to the finished product. 
<other information here>
The github for the source code is here and i will make you a contributor on the github if you agree to help so that you can modify the source code. 
https://github.com/MadamJazzy/JazzyCogs/tree/master/RevImage

**Comment by MadamJazzy** [comment]
Also unsure how to make it install bs4 when they install the cog. Needs to run "pip3 install bs4" so that the cog will work correctly. Right now its a manual install

**Comment by tekulvw** [comment]
Add `"requirements": ["bs4", ]` to your info.json

**Comment by MadamJazzy** [comment]
This cog has been created, I have completed this project on my own and therefor no longer did it to be created. It is able to be downloaded by those who want it by doing [p]redp search revimage in the red cogs server. Thank you everyone
