### ISSUE TITLE
Snail Race

### ISSUE THREAD

**Issue by XxPoNaGeXx** [Cog-Creators/Cog-Board#57]
## Description of cog:

A cog that you can type [p]start snail race, here is an example: http://i.imgur.com/1WAUMse.png

The prize in this case would be the default red economy system

**Comment by Real-Wizard** [comment]
Well iam not sure `I` can code that but why not just use the bot?

**Comment by XxPoNaGeXx** [comment]
I prefer to only have one bot on my server which is mines. It makes the server more professional looking

**Comment by Mippy** [comment]
What are you looking prizes to be?

**Comment by XxPoNaGeXx** [comment]
In looking for the prizes to be red credits

**Comment by Redjumpman** [comment]
Done. Made this on my stream. You can find it on my repo here: https://github.com/Redjumpman/Jumper-Cogs
