### ISSUE TITLE
Marriage Cog

### ISSUE THREAD

**Issue by XxPoNaGeXx** [Cog-Creators/Cog-Board#61]
## Description of cog:

Users will be able to type `?propose <user>` and then the user they proposed to will need to accept. Those users will not yet be married. A priest e.g. staff will need to then marry them together. 

If a user tries to propose to a member it must say "@<user> is already married to @<user> are you sure you still want to propose?" 

Then we will be able to have a <divorce> command. 

This all must make use of embeds 

## API's or other information for cog:

Marriage costs 100 coins from red economy 

## Other info (Bounty, issues, ETC):

Willing to pay £2 for this 

Message me on Discord: Kyle#9494

**Comment by XxPoNaGeXx** [comment]
Please close this, I found a cog that does this haha

**Comment by Kowlin** [comment]
As you wish.
