### ISSUE TITLE
Image Approval On Certain Channel

### ISSUE THREAD

**Issue by XxPoNaGeXx** [Cog-Creators/Cog-Board#68]
## Description of cog:

To prevent any underaged NSFW images on an NSFW channel. All images must be approved. So once a user uploads the image the bot will auto delete it and then tell the user it needs to be approved. It can then be messaged to a #staff channel where a staff member needs to type [p](img)approve <@user> and then the bot will upload it back to the NSFW channel Saying @User has uploaded: with the image file/imgur link

## Other info (Bounty, issues, ETC):

**Comment by retke** [comment]
I can do this, contact me on discord on [Red's server](https://discord.gg/red). My name is El Laggron#7757

**Comment by Aioxas** [comment]
Any updates on this @retke actively working on, stale?

**Comment by retke** [comment]
@Aioxas he never contacted me

**Comment by Aioxas** [comment]
Closed due to inactivity/staleness then. If the author or someone decides that this should be re-opened, ping me in discord @Axas#7680 and I will reopen.
