### ISSUE TITLE
Branches Cog [Paid Job]

### ISSUE THREAD

**Issue by BlushBerry** [Cog-Creators/Cog-Board#69]
## Branch Assigner Cog

The way our community is going to work is we are going to have "Branches" that users can join which are basically roles
Which will allow them to be paired up with people who play the same game. Our community will be split up into seperate branches
with what we call "Branch Leaders" they are the ones who will be running that particular branch. To automate the process we need something
Like a cog to manage all this so if a user wants to join a branch they don't need anyone to assign them the role.
 
I'll be calling the join-able roles branches.

Price is negotiable to complete this cog and if you're interested in further work I'd be happy to pay for additional cogs.

[p]branch -- List's all available commands. (Anyone can use this)
[p]branch add <role> <alias>-- adds a role to join under an alias. (Redbot Admin Role Only)
[p]branch remove <alias> -- removes the role to join from the list. (Redbot Admin Role Only)
[p]branch join <alias>-- Join's a branch. (Anyone can use this)
[p]branch leave <alias> -- Leave's a branch. (Anyone can use this)
[p]branch set cooldown <integer minutes> -- Set's the cooldown timer for when a user can join or leave thier current branch. (Redbot Admin Role Only)
[p]branch set maxbranch <integer> -- How many branches globally anyone can join at a time. (If they try to join too many it will inform them to leave a branch before joining a new one) (Redbot Admin Role Only) (Default True)
[p]branch set cooldownmsgdm <boolean> -- Does the message DM or display in the server? (Redbot Admin Role Only) (Default False)
[p]branch set cooldownmsg <string> -- Message that is displayed when a user tries to join too many branches. (Redbot Admin Role Only) (Default: "You are in too many branches @mention, Please leave one before joining another.)
[p]branch cooldown <alias> -- Display how much time they have left before they can join another branch (Must be displayed in this format <integer> Months, <integer> Days, <integer> Minutes, <integer> Seconds) (Anyone can use this)
[p]branch time <alias> -- Display how long they themself have been in that branch, Time resets if they leave the branch. If they are apart of multiple branches allow them to pick from a list for the time. (Anyone can use this)
[p]branch checktime <user> -- Check how long a user has been in a branch (Redbot Admin Role Only)
[p]branch checkcd <user> <alias> -- Check the cooldown of a user for the selected branch.
[p]branch list -- List's all available branches to join. (Anyone can use this)

If you are interested in this job please contact me on discord: Polygon#7877
Paypal or Google wallet is preferred methods of pay.

**Comment by tekulvw** [comment]
Do you want this for V2 or V3?

**Comment by BlushBerry** [comment]
Probably V2 for now but later down the road once V3 becomes in a more stable state I'll pay again to have it be converted for V3.

**Comment by Tobotimus** [comment]
:wave: I am starting on this cog for V2.

**Comment by BlushBerry** [comment]
I never ended up updating this but, This job has been completed for quite a while and is no longer available.
