### ISSUE TITLE
Remove Commands from Help

### ISSUE THREAD

**Issue by MagicNinja123** [Cog-Creators/Cog-Board#7]
Well a Cog That Removes Disabled Commands From `[p]command disable`

**Comment by Nerdietony** [comment]
can we lock this? It's a duplicate

**Comment by MagicNinja123** [comment]
Its Not

**Comment by MagicNinja123** [comment]
The Other One Is To Create a Custom Cog , This Is With The Original Help But Removes Disabled Commands
