### ISSUE TITLE
Cryptocurrency

### ISSUE THREAD

**Issue by rojassartorio** [Cog-Creators/Cog-Board#76]
## Description of cog: 

Hello, someone can make a cog to consume data from a site with some commands.
Example: !btc, ...
Return: BTC (Bitcoin) is at 4000USD
Example: !etc
Return: ETH (Ethereum) is at 400USD.
Example: !ltc
Return: LTC (Litecoin) is at XXXUSD.

of the page https://coinmarketcap.com/

## API's or other information for cog:
<script type="text/javascript" src="https://files.coinmarketcap.com/static/widget/currency.js"></script>
<div class="coinmarketcap-currency-widget" data-currency="bitcoin" data-base="USD" ></div>

https://coinmarketcap.com/currencies/bitcoin/#tools Customizable.

## Other info (Bounty, issues, ETC):
It is very necessary and will be used a lot ..

**Comment by atiwiex** [comment]
I have a cog for btc prices and other btc related stuff. https://github.com/atiwiex/Ati-Cogs/

**Comment by rojassartorio** [comment]
Has a guide of the commands I will try to implement now.

**Comment by rojassartorio** [comment]
And how can I get with parameters of each of these values?
Creo que es fácil pero no logro hacerlo.
https://api.coinmarketcap.com/v1/ticker/

**Comment by atiwiex** [comment]
The cog is built for the API that I used in the first place

**Comment by rojassartorio** [comment]
Can you give me a hand? Help me a little ??

https://coinmarketcap.com/api/

**Comment by atiwiex** [comment]
I'll mess with it but the cog is built for that api

**Comment by rojassartorio** [comment]
I need to pass parameters with the command. And that I throw the values ​​in usd of coinmarketcap, this is the complete api of the page that returns all the values. >> https://coinmarketcap.com/api/ 
No hablo bien inglés, use Google Translate.

**Comment by rojassartorio** [comment]
I integrate your COG to my redBot that is running and is perfect but only blockchain I need to coinmarketcap

**Comment by atiwiex** [comment]
No se puede cambiar a coinmarketcap como el diente se construye utilizando la cadena de bloqueo api.

**Comment by rojassartorio** [comment]
Si entiendo eso, pero yo estoy tratando de construir, modificar el código para consumir los datos de la api de coinmarketcap .  //// If I understand that, but I am trying to build, modify the code to consume the data of the api of coinmarketcap, I need help from you.

**Comment by atiwiex** [comment]
El api no es cambiable y no voy a ayudarte a cambiarlo.

**Comment by rojassartorio** [comment]
Bueno! Gracias!

**Comment by atiwiex** [comment]
I think this is closeable.

**Comment by rojassartorio** [comment]
Bueno! Gracias!

**Comment by rojassartorio** [comment]
Cerrar que?

**Comment by rojassartorio** [comment]
Porque no quieres ayudarme a cambiar?! Que le paso a tu corazón?

**Comment by atiwiex** [comment]
Todavía tengo mi corazón y lo diré una vez más el api en uso no se está cambiando.

**Comment by rojassartorio** [comment]
Tratare de modificar y hacerlo yo mismo para coinmarketcap. GRACIAS *

**Comment by atiwiex** [comment]
Yo no recomendaría editarlo.

**Comment by rojassartorio** [comment]
Porque no, es casi lo mismo, lo necesito recuperar filtrando por symbol y recuperar price_usd. Ejemplo symbol:BTC print price_usd

**Comment by atiwiex** [comment]
No voy a ayudarle a editar el diente ya que sólo soporta blockchain.

**Comment by rojassartorio** [comment]
No ME ayudes. No importa, pero  LO HARÉ YO, recuerda eso. ;<

**Comment by atiwiex** [comment]
Ok, no voy a proporcionar apoyo a lo que quiebre.

**Comment by Bakersbakebread** [comment]
is this being worked on?
