### ISSUE TITLE
[Paid Job] Text chat deactivation based on stream activity trigger

### ISSUE THREAD

**Issue by FFZendikar** [Cog-Creators/Cog-Board#77]
## Description of cog:

I'm looking for a cog that can deactivate (or rather remove all permissions from a text channel/multiple channels) during when a stream from twitch.tv is active, and reactivated when it is offline.

## API's or other information for cog:

Will obviously need twitch API integration.

## Other info (Bounty, issues, ETC):

Not much else, should be adjustable to change which stream to look at, plus send a message for deactivation and reactivation. 

Bounty is $50, would like this done as soon as possible.

**Comment by Tobotimus** [comment]
:wave: I'd happily write this for you mate.

**Comment by Tobotimus** [comment]
@FFZendikar Just remining you, this can be closed now 😃
