### ISSUE TITLE
[Suggestion][Unpaid][V3]

### ISSUE THREAD

**Issue by Jan200101** [Cog-Creators/Cog-Board#78]
## Description of cog:

a async to rewrite cog using [async2rewrite](https://github.com/TheTrain2000/async2rewrite) to load async cogs on V3.

## API's or other information for cog:

[async2rewrite](https://github.com/TheTrain2000/async2rewrite)

**Comment by tekulvw** [comment]
No sentry, the changes are way too complex for this idea to support any but the simplest of cogs. It has no true use and you'll spend more time trying to make this than you will just converting your stuff.
