### ISSUE TITLE
Custom Help

### ISSUE THREAD

**Issue by MagicNinja123** [Cog-Creators/Cog-Board#8]
a Way To Create a Completly New Help Command

*Edit:
Assigned to @Nerdietony and @Kowlin
-- Kowlin*

**Comment by Nerdietony** [comment]
I'm on this

**Comment by SHADOW6** [comment]
On our server, I've disabled the [p]help commands with perms for @everyone 
But still have staff able to use it. 
Then we set up a custom table under [p]cmds which displays the following in a private msg.
https://puu.sh/uqDpI/8fb92d0257.png
http://puu.sh/usrRN/138a5ffe46.png

**Comment by Testdude3234** [comment]
I also want this too 👍

**Comment by Nerdietony** [comment]
https://github.com/Nerdietony/Nerdie-Cogs

it's called customhelp

It's pretty news so wait for the rest to be pushed tonight.

**Comment by Testdude3234** [comment]
@Nerdietony Customhelp broke the actual help command, Hope it's fixed.

**Comment by Nerdietony** [comment]
How so @testdude3234

**Comment by Testdude3234** [comment]
Simply, if you unload the cog, the help does not send any DM

btw, what's the new update going to have? The ability to edit the embed title and footer?  Also allow support for mutiple "pages of help"

**Comment by Nerdietony** [comment]
Yes and yes and u need to keep it loaded for it to work

**Comment by MagicNinja123** [comment]
Nerdie Please Make It Possible To Make It IN a Dm

**Comment by MagicNinja123** [comment]
And Make It Possible To Get It Back To Original

**Comment by WreckRox** [comment]
I've tried creating a custom help command tho 
http://i.wreckroxd.gq/i/i/big/72561b035902fa01f5c4920fee00f95e.PNG

**Comment by WreckRox** [comment]
@MagicNinja123 you could try replacing 
`await self.bot.send_message(channel, embed=embed)`
 in line 96 to 
`await self.bot.whisper( embed=embed)` 
and in line 101 
`await self.bot.whisper(msg)`

**Comment by Kowlin** [comment]
Please refrain from posting anything but suggestions and updates in these issues. Doing that will result in the issue being locked.

**Comment by MagicNinja123** [comment]
@Nerdietony The Cog Also Disables [p]help {command}

**Comment by Nerdietony** [comment]
Ok skinny divas, listen up! If you want to enable the old help command then unload the cog and restart your bot.  Next, the cog deletes THE ENTIRE HELP COMMAND so if you want to use a custom help, you're gonna have to forfeit it. 

Also, the rest of the settings will be here tonight or tomorrow afternoon. I'm a busy teen.

P.S. @WreckRox Don't go telling ppl to edit my god damn code unless it's a PR. There's already a toggle to sethelp to enable it to be in DM. kthxbai

**Comment by Chovin** [comment]
@Nerdietony @MagicNinja123 @WreckRox, This is not a place to support your cogs. Please take this conversation to your repo / support area. I've made an issue on your repo and we have a Cog-Support server for this.

Please keep keep the conversations here relevant to cog requests and their requested functionalities.

**Comment by QingyuChai** [comment]
@MagicNinja123 if yo are interested, I just released a cog that basically embeds the help page and removes the descriptions. You can find it [here](https://github.com/QingyuChai/RiceCogs/tree/master/embedhelp). It allows for users to toggle if the help message is sent into DM or not. 
Note: It might not work if your help message is too long

**Comment by QingyuChai** [comment]
I already had this for a while, and decided to release it today

**Comment by MagicNinja123** [comment]
Fwied ( I Think ) Thx But I Needed The Custom Command To Remove Commands From Help And To Make It Fancier btw Ty

**Comment by Chovin** [comment]
removing commands from help is #7
