### ISSUE TITLE
ELO-based Cog 

### ISSUE THREAD

**Issue by KeatenStJ** [Cog-Creators/Cog-Board#89]
## Description of cog:
An ELO based cog to be used in discord to have a ranking of people. 
<your description here>
Pretty self explanatory. Need it to be customizable. Being able to enter in player 1 loses player 2 wins and have a standings page ongoing that can be resettable from the owner.
## API's or other information for cog:

<APIs and integrations here>

## Other info (Bounty, issues, ETC):
50$ US. Need some ASAP, can chat over discord all the fine details.
<other information here>

**Comment by calebj** [comment]
I can start writing this as soon as I get off of work. What's your Discord handle?

**Comment by KeatenStJ** [comment]
Keaten#7893

**Comment by calebj** [comment]
This commission is complete.
