### ISSUE TITLE
Image poster 

### ISSUE THREAD

**Issue by Adeft** [Cog-Creators/Cog-Board#9]
Would it be hard to make a cog that posts images? Eg. You make different folders with whatever name you want: cat,  dogs, girls, cars. Inside the folder there is a notebook with picture url's (imgur etc) or pictures itself. When people do !cars it picks a random picture from the car folder and post it.

**Comment by Nerdietony** [comment]
seems interesting

**Comment by MagicNinja123** [comment]
I Beileve another bot has the fueture so no dont think its hard

**Comment by Nerdietony** [comment]
it is. More likely, i won't be doing this but i came up with a system of how to do this or how it might work...

**Comment by tmercswims** [comment]
I have this already, almost exactly like you described: http://cogs.red/cogs/tmercswims/tmerc-cogs/randimage/
