### ISSUE TITLE
Warning system

### ISSUE THREAD

**Issue by tbstewa** [Cog-Creators/Cog-Board#90]
## Description of cog:
Looking for a system to warn and store/display the number of warnings along with all prior warning reasons when looking for a users prior warnings

## API's or other information for cog:
Data must be stored via json and retrievable/editable

## Other info (Bounty, issues, ETC):
100% willing to discuss a bounty if a creator is willing to work on the project. Preferred contact would be via discord: tbstewa#3094

**Comment by hunter30022** [comment]
Ill give this a try. Don't need money cuz im not guaranteeing anything.

**Comment by Mippy** [comment]
I added you as a friend on Discord (you have server DMs disabled) message me when you're available.

Mippy#8370

**Comment by retke** [comment]
I made this cog! It's finished (almost) and I will publish it very soon, I will post again when this will be ready

**Comment by hunter30022** [comment]
FML

**Comment by tbstewa** [comment]
@retke your cog looks like it could work, but only if there was a command to check a person's history. Mod log is great and all, but when you have a server with over 20k members, it's a little tough to track through that

**Comment by hunter30022** [comment]
@tbstewa there is a warning checker lol

**Comment by hunter30022** [comment]
Either way, if you are willing to wait a few more days, I am now actively working to get this warn cog complete @tbstewa It will be a lot more lightweight that rekte's because it will literally just be warn and listwarns.

**Comment by retke** [comment]
Lol that's exactly what I have done

**Comment by retke** [comment]
Ok the cog is done, now I can wait for orels1 approve to add it to red portal (should be good as he's aware of these cogs for a long time). You can already add the cog using downloader (oh and about your last comment, yes, you can check users warning with a nice system, with reactions, you can also edit reasons and delete some) I'd suggest you to try yourself :D 

`[p]cog repo add Laggrons-Dumb-Cogs https://github.com/retke/Laggrons-Dumb-Cogs
[p]cog install Laggrons-Dumb-Cogs bettermod`

If you have any question, suggestion or bug to report, I have a [support server](https://discord.gg/WsTGeQM) you can join!

**Comment by hunter30022** [comment]
If you still want just warns and reports, I stitched @retke's bettermod cog into just warnings. Either way, please close this issue as resolved :D 
Cheers @tbstewa 
[p]cog repo add Banana-Cogs https://github.com/hunter30022/Banana-Cogs
[p]cog install Banana-Cogs uwarn

**Comment by retke** [comment]
Seems he died

**Comment by hunter30022** [comment]
I would have to agree with you.

**Comment by tbstewa** [comment]
I didn't really die, well maybe... but solved thanks guys
